# Generated by Django 4.0.4 on 2022-05-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='sss', upload_to='Post/images/'),
            preserve_default=False,
        ),
    ]
