# Generated by Django 4.0.4 on 2022-05-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Address'),
        ),
    ]
