# Generated by Django 4.0.4 on 2022-05-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Price'),
        ),
    ]
