# Generated by Django 4.0.4 on 2022-05-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_propertyimage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(max_length=5000, verbose_name='Text'),
        ),
    ]
