# Generated by Django 4.0.4 on 2022-05-20 09:19

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_property_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='property',
            managers=[
                ('people', django.db.models.manager.Manager()),
            ],
        ),
    ]
