# Generated by Django 4.0.4 on 2022-05-23 16:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0008_alter_property_created_at_alter_property_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='Property_Hotel',
        ),
    ]
