# Generated by Django 4.0.4 on 2022-05-23 17:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0009_rename_property_property_hotel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property_Hotel',
            new_name='Property',
        ),
    ]
