# Generated by Django 4.0.4 on 2022-05-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_rename_property_hotel_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertybook',
            name='count',
        ),
        migrations.AddField(
            model_name='propertybook',
            name='children',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (2, 2), (2, 2)], default=0),
        ),
        migrations.AddField(
            model_name='propertybook',
            name='guest',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (2, 2), (2, 2)], default=1),
        ),
    ]
