# Generated by Django 4.0.4 on 2022-05-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(max_length=10000, verbose_name='Text'),
        ),
    ]
