# Generated by Django 4.0.4 on 2022-06-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_alter_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, null=True),
        ),
    ]
