# Generated by Django 4.0.4 on 2022-06-04 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_property_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertybook',
            options={},
        ),
        migrations.AlterField(
            model_name='propertybook',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End Date'),
        ),
    ]
