# Generated by Django 4.0.4 on 2022-06-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_alter_propertybook_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertybook',
            options={'ordering': ['-id']},
        ),
    ]
