# Generated by Django 4.0.4 on 2022-07-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_alter_propertybook_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyreview',
            name='review',
        ),
    ]
